services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecommerce
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecomerce_go
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
